version: '3.4'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/opt/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: bash ./scripts/runserver.sh

  db:
    image: postgres
    env_file:
      - ./backend/env/db.env

  backend:
    build: ./backend
    env_file:
      - ./backend/env/db.env
    volumes:
      - ./backend:/opt/backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: bash ./scripts/runserver.sh
